# Generated by Django 3.1.2 on 2020-10-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.TextField()),
                ('street', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('zip', models.TextField(max_length=10)),
                ('website', models.TextField(blank=True, max_length=150, null=True, verbose_name='website')),
                ('phone', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
