# Generated by Django 3.1.2 on 2020-10-27 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0002_auto_20201026_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='credit_cards',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_directory_path'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_owner',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='noise_level',
            field=models.IntegerField(blank=True, choices=[(1, 'quiet'), (2, 'comfort'), (3, 'noisy')], null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_level',
            field=models.IntegerField(blank=True, choices=[(1, '$1-$10'), (2, '$11-$30'), (3, '$30-$50')], null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reservations',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='take_away',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='waiter_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wifi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
