export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const GET_BEST_RESTAURANTS = "GET_BEST_RESTAURANTS";
export const CREATE_NEW_RESTAURANT = "CREATE_NEW_RESTAURANT";
export const GET_TOKEN = "GET_TOKEN";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTRATION = "USER_REGISTRATION";
export const GET_USER = "GET_USER";
